extends:
  - stylelint-config-standard-scss
  - stylelint-config-recess-order
rules:
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - apply
        - layer
        - responsive
        - screen
        - tailwind
        - variants
  selector-class-pattern: null
  value-keyword-case:
    - lower
    - ignoreKeywords:
        - /A(3|4|5)|(B|JIS-B)(4|5)/
