extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss
  - stylelint-config-recess-order
rules:
  selector-class-pattern: null
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - apply
        - layer
        - responsive
        - screen
        - tailwind
        - variants
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - apply
        - layer
        - responsive
        - screen
        - tailwind
        - variants
