extends:
  - stylelint-config-standard
  - stylelint-config-recess-order
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - apply
        - layer
        - responsive
        - screen
        - tailwind
        - variants
